Repository fga-eps-mds/2020.2-Eccoar, pull requests merged in 2021-03, with the labels that each got.

#61 [REVIEW] #56 template de pull request
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Gerenciamento, documentation, help wanted

#64 [REVIEW] #52 Criar página da identidade visual
  docs/produto/identidadevisual.md
  mkdocs.yml
Labels: documentation

#65 [REVIEW] Documento de Arquitetura
  docs/assets/img/produtos/DataModel.png
  docs/assets/img/produtos/backArquitetura.png
  docs/assets/img/produtos/docArquitetura.png
  docs/assets/img/produtos/front.png
  docs/produto/documento-arquitetura.md
  mkdocs.yml
Labels: Architect, documentation

#62 Solve #50 - Backlog do Produto
  .gitignore
  docs/produto/backlogProduto.md
  docs/requitos/benchmarking.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation

#74 Solve #53 Protótipo de alta fidelidade
  docs/produto/identidadevisual.md
  docs/produto/prototipo.md
  docs/projeto/documento-arquitetura.md
  docs/projeto/tap.md
  mkdocs.yml
Labels: Ideação, documentation, protótipo

#81 Documentação Planning Sprint 4
  docs/sprints/3/planning.md
  docs/sprints/4/planning.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation

#86 Adicionar Logo e nome do Projeto no Readme
  README.md
Labels: documentation

#82 [REVIEW] #68 Estilização da Wiki
  docs/assets/css/extra.css
  docs/assets/css/landing-page.css
  docs/assets/img/background.jpg
  docs/assets/img/doc.svg
  docs/assets/img/favicon.ico
  docs/assets/img/github.svg
  docs/assets/img/isotipo.png
  docs/assets/img/logo.png
  docs/contribuicao/contribuicao.md
  docs/index.html
  mkdocs.yml
Labels: MDS, documentation

#92 Adiciona backlog sumido
  mkdocs.yml
Labels: bug

#95 Solve #67 - Criar tabela de análise de EVM
  docs/projeto/evm.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation

#96 Solve #70 Estudo de testes do front
  docs/contribuicao/testes-front.md
  mkdocs.yml
Labels: Front-end, documentation

#106 Solve #54 Realizar testes do protótipo
  docs/assets/img/usuario/comquefrequencia.png
  docs/assets/img/usuario/mapadecores.png
  docs/assets/img/usuario/qrcodeprototipo.png
  docs/assets/img/usuario/qualseugenero.png
  docs/assets/img/usuario/qualsuaidade.png
  docs/usuario/testesusabilidade.md
  mkdocs.yml
Labels: Dívida Técnica, documentation, protótipo, validação

#108 Solve #105 Documentação Planning Sprint 5
  docs/sprints/4/planning.md
  docs/sprints/5/planning.md
  mkdocs.yml
Labels: Product Owner, documentation

#107 Solve #104 Documentação Review Sprint 4
  docs/assets/img/sprints/4/burndown.png
  docs/assets/img/sprints/4/conhecimento.png
  docs/assets/img/sprints/4/conhecimentoGraphic.png
  docs/assets/img/sprints/4/cumulativeFlow.png
  docs/assets/img/sprints/4/cycleTime.png
  docs/assets/img/sprints/4/cycleTimeReview.png
  docs/assets/img/sprints/4/humor.png
  docs/assets/img/sprints/4/retrospectiva.png
  docs/assets/img/sprints/4/risk.png
  docs/assets/img/sprints/4/velocity.png
  docs/sprints/4/retrospectiva.md
  docs/sprints/4/review.md
  mkdocs.yml
Labels: Scrum Master, documentation

#110 Solve #100 Rastreamento da Arquitetura
  docs/projeto/rastro-arquitetura.md
  mkdocs.yml
Labels: Architect, documentation

#109 Solve #99 Preparar documentações para a R1
  docs/contribuicao/contribuicao.md
  docs/index.html
  docs/intro.md
  docs/metodologia/templates/planning.md
  docs/produto/backlogAceitacao/backlogProduto.md
  docs/produto/backlogProduto.md
  docs/produto/documento-visao.md
  docs/produto/roadmap.md
  docs/projeto/tap.md
  docs/requitos/benchmarking.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation

#120 Documento de critérios de aceitação
  docs/produto/backlogAceitacao/backlogProduto.md
  docs/produto/backlogAceitacao/criteriosAceitacao.md
  docs/produto/roadmap.md
  docs/projeto/evm.md
  docs/projeto/tap.md
Labels: Product Owner, documentation

#121 Create LICENSE
  LICENSE
Labels: documentation

#123 Solve #116 - Documentação Planning Sprint 6
  docs/sprints/6/planning.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation
