Repository fga-eps-mds/2020.2-Eccoar, pull requests merged in 2021-02, with the labels that each got.

#28 Documentação Planning Sprint 1
  docs/sprints/1/planning.md
Labels: Product Owner, documentation

#42 Planning sprint 2
  docs/metodologia/templates/planning.md
  docs/sprints/1/planning.md
  docs/sprints/2/planning.md
  mkdocs.yml
Labels: Product Owner, documentation

#43 [REVIEW] #33 - Termo de Abertura de Projeto
  docs/produto/tap.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation

#44 [REVIEW] #37 Requisitos de Questionario
  docs/produto/requisitos/requisitosQuestionario.md
  mkdocs.yml
Labels: documentation

#59 Planning sprint 3
  docs/metodologia/gerenciaRisco.md
  docs/metodologia/templates/planning.md
  docs/sprints/3/planning.md
  mkdocs.yml
Labels: Product Owner, documentation

#46 [REVIEW] 36 requisitos de benchmarking
  docs/produto/requisitos/benchmarking.md
  mkdocs.yml
Labels: Gerenciamento, Product Owner, documentation
